/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Apteco.ApiRescheduler.ApiClient.Client;
using Apteco.ApiRescheduler.ApiClient.Model;

namespace Apteco.ApiRescheduler.ApiClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ITemporaryFilesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns the contents of a temporary file with the given id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file to return the contents for</param>
        /// <param name="temporaryToken">Temporary authentication token to be used for access to the resource when Bearer authentication is not suitable (i.e. direct browser download). Temporary tokens can be obtained from the TemporaryTokens api endpoint. (optional)</param>
        /// <param name="contentDispositionFileName">The file name to add to the Content-Disposition HTTP header on the response (optional)</param>
        /// <returns>byte[]</returns>
        byte[] TemporaryFilesGetTemporaryFile (string dataViewName, string id, string temporaryToken = null, string contentDispositionFileName = null);

        /// <summary>
        /// Returns the contents of a temporary file with the given id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file to return the contents for</param>
        /// <param name="temporaryToken">Temporary authentication token to be used for access to the resource when Bearer authentication is not suitable (i.e. direct browser download). Temporary tokens can be obtained from the TemporaryTokens api endpoint. (optional)</param>
        /// <param name="contentDispositionFileName">The file name to add to the Content-Disposition HTTP header on the response (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> TemporaryFilesGetTemporaryFileWithHttpInfo (string dataViewName, string id, string temporaryToken = null, string contentDispositionFileName = null);
        /// <summary>
        /// Returns the contents of a temporary file part with the given id and part number
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to return the contents for</param>
        /// <returns>byte[]</returns>
        byte[] TemporaryFilesGetTemporaryFilePart (string dataViewName, string id, int? partNumber);

        /// <summary>
        /// Returns the contents of a temporary file part with the given id and part number
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to return the contents for</param>
        /// <returns>ApiResponse of byte[]</returns>
        ApiResponse<byte[]> TemporaryFilesGetTemporaryFilePartWithHttpInfo (string dataViewName, string id, int? partNumber);
        /// <summary>
        /// Creates or updates a temporary file with the given id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file to create or update</param>
        /// <returns>TemporaryFile</returns>
        TemporaryFile TemporaryFilesUpsertTemporaryFile (byte[] file, string dataViewName, string id);

        /// <summary>
        /// Creates or updates a temporary file with the given id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file to create or update</param>
        /// <returns>ApiResponse of TemporaryFile</returns>
        ApiResponse<TemporaryFile> TemporaryFilesUpsertTemporaryFileWithHttpInfo (byte[] file, string dataViewName, string id);
        /// <summary>
        /// Creates or updates part of a temporary file with the given id and part number
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to create or update.  This is zero-based</param>
        /// <param name="finalPart">Whether this part is the final part and the full temporary file should be assembled.  If this is not specified it defaults to false.  If this is set to true all parts from 0 up to this partIndex must already exist (optional)</param>
        /// <returns>TemporaryFilePart</returns>
        TemporaryFilePart TemporaryFilesUpsertTemporaryFilePart (byte[] file, string dataViewName, string id, int? partNumber, bool? finalPart = null);

        /// <summary>
        /// Creates or updates part of a temporary file with the given id and part number
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to create or update.  This is zero-based</param>
        /// <param name="finalPart">Whether this part is the final part and the full temporary file should be assembled.  If this is not specified it defaults to false.  If this is set to true all parts from 0 up to this partIndex must already exist (optional)</param>
        /// <returns>ApiResponse of TemporaryFilePart</returns>
        ApiResponse<TemporaryFilePart> TemporaryFilesUpsertTemporaryFilePartWithHttpInfo (byte[] file, string dataViewName, string id, int? partNumber, bool? finalPart = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Returns the contents of a temporary file with the given id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file to return the contents for</param>
        /// <param name="temporaryToken">Temporary authentication token to be used for access to the resource when Bearer authentication is not suitable (i.e. direct browser download). Temporary tokens can be obtained from the TemporaryTokens api endpoint. (optional)</param>
        /// <param name="contentDispositionFileName">The file name to add to the Content-Disposition HTTP header on the response (optional)</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> TemporaryFilesGetTemporaryFileAsync (string dataViewName, string id, string temporaryToken = null, string contentDispositionFileName = null);

        /// <summary>
        /// Returns the contents of a temporary file with the given id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file to return the contents for</param>
        /// <param name="temporaryToken">Temporary authentication token to be used for access to the resource when Bearer authentication is not suitable (i.e. direct browser download). Temporary tokens can be obtained from the TemporaryTokens api endpoint. (optional)</param>
        /// <param name="contentDispositionFileName">The file name to add to the Content-Disposition HTTP header on the response (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> TemporaryFilesGetTemporaryFileAsyncWithHttpInfo (string dataViewName, string id, string temporaryToken = null, string contentDispositionFileName = null);
        /// <summary>
        /// Returns the contents of a temporary file part with the given id and part number
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to return the contents for</param>
        /// <returns>Task of byte[]</returns>
        System.Threading.Tasks.Task<byte[]> TemporaryFilesGetTemporaryFilePartAsync (string dataViewName, string id, int? partNumber);

        /// <summary>
        /// Returns the contents of a temporary file part with the given id and part number
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to return the contents for</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        System.Threading.Tasks.Task<ApiResponse<byte[]>> TemporaryFilesGetTemporaryFilePartAsyncWithHttpInfo (string dataViewName, string id, int? partNumber);
        /// <summary>
        /// Creates or updates a temporary file with the given id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file to create or update</param>
        /// <returns>Task of TemporaryFile</returns>
        System.Threading.Tasks.Task<TemporaryFile> TemporaryFilesUpsertTemporaryFileAsync (byte[] file, string dataViewName, string id);

        /// <summary>
        /// Creates or updates a temporary file with the given id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file to create or update</param>
        /// <returns>Task of ApiResponse (TemporaryFile)</returns>
        System.Threading.Tasks.Task<ApiResponse<TemporaryFile>> TemporaryFilesUpsertTemporaryFileAsyncWithHttpInfo (byte[] file, string dataViewName, string id);
        /// <summary>
        /// Creates or updates part of a temporary file with the given id and part number
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to create or update.  This is zero-based</param>
        /// <param name="finalPart">Whether this part is the final part and the full temporary file should be assembled.  If this is not specified it defaults to false.  If this is set to true all parts from 0 up to this partIndex must already exist (optional)</param>
        /// <returns>Task of TemporaryFilePart</returns>
        System.Threading.Tasks.Task<TemporaryFilePart> TemporaryFilesUpsertTemporaryFilePartAsync (byte[] file, string dataViewName, string id, int? partNumber, bool? finalPart = null);

        /// <summary>
        /// Creates or updates part of a temporary file with the given id and part number
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to create or update.  This is zero-based</param>
        /// <param name="finalPart">Whether this part is the final part and the full temporary file should be assembled.  If this is not specified it defaults to false.  If this is set to true all parts from 0 up to this partIndex must already exist (optional)</param>
        /// <returns>Task of ApiResponse (TemporaryFilePart)</returns>
        System.Threading.Tasks.Task<ApiResponse<TemporaryFilePart>> TemporaryFilesUpsertTemporaryFilePartAsyncWithHttpInfo (byte[] file, string dataViewName, string id, int? partNumber, bool? finalPart = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class TemporaryFilesApi : ITemporaryFilesApi
    {
        private Apteco.ApiRescheduler.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TemporaryFilesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TemporaryFilesApi(String basePath)
        {
            this.Configuration = new Apteco.ApiRescheduler.ApiClient.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Apteco.ApiRescheduler.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemporaryFilesApi"/> class
        /// </summary>
        /// <returns></returns>
        public TemporaryFilesApi()
        {
            this.Configuration = Apteco.ApiRescheduler.ApiClient.Client.Configuration.Default;

            ExceptionFactory = Apteco.ApiRescheduler.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemporaryFilesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TemporaryFilesApi(Apteco.ApiRescheduler.ApiClient.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Apteco.ApiRescheduler.ApiClient.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Apteco.ApiRescheduler.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Apteco.ApiRescheduler.ApiClient.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Apteco.ApiRescheduler.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Returns the contents of a temporary file with the given id 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file to return the contents for</param>
        /// <param name="temporaryToken">Temporary authentication token to be used for access to the resource when Bearer authentication is not suitable (i.e. direct browser download). Temporary tokens can be obtained from the TemporaryTokens api endpoint. (optional)</param>
        /// <param name="contentDispositionFileName">The file name to add to the Content-Disposition HTTP header on the response (optional)</param>
        /// <returns>byte[]</returns>
        public byte[] TemporaryFilesGetTemporaryFile (string dataViewName, string id, string temporaryToken = null, string contentDispositionFileName = null)
        {
             ApiResponse<byte[]> localVarResponse = TemporaryFilesGetTemporaryFileWithHttpInfo(dataViewName, id, temporaryToken, contentDispositionFileName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the contents of a temporary file with the given id 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file to return the contents for</param>
        /// <param name="temporaryToken">Temporary authentication token to be used for access to the resource when Bearer authentication is not suitable (i.e. direct browser download). Temporary tokens can be obtained from the TemporaryTokens api endpoint. (optional)</param>
        /// <param name="contentDispositionFileName">The file name to add to the Content-Disposition HTTP header on the response (optional)</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > TemporaryFilesGetTemporaryFileWithHttpInfo (string dataViewName, string id, string temporaryToken = null, string contentDispositionFileName = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFile");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFile");

            var localVarPath = "./{dataViewName}/TemporaryFiles/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (temporaryToken != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "temporaryToken", temporaryToken)); // query parameter
            if (contentDispositionFileName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "contentDispositionFileName", contentDispositionFileName)); // query parameter
            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TemporaryFilesGetTemporaryFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Returns the contents of a temporary file with the given id 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file to return the contents for</param>
        /// <param name="temporaryToken">Temporary authentication token to be used for access to the resource when Bearer authentication is not suitable (i.e. direct browser download). Temporary tokens can be obtained from the TemporaryTokens api endpoint. (optional)</param>
        /// <param name="contentDispositionFileName">The file name to add to the Content-Disposition HTTP header on the response (optional)</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> TemporaryFilesGetTemporaryFileAsync (string dataViewName, string id, string temporaryToken = null, string contentDispositionFileName = null)
        {
             ApiResponse<byte[]> localVarResponse = await TemporaryFilesGetTemporaryFileAsyncWithHttpInfo(dataViewName, id, temporaryToken, contentDispositionFileName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns the contents of a temporary file with the given id 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file to return the contents for</param>
        /// <param name="temporaryToken">Temporary authentication token to be used for access to the resource when Bearer authentication is not suitable (i.e. direct browser download). Temporary tokens can be obtained from the TemporaryTokens api endpoint. (optional)</param>
        /// <param name="contentDispositionFileName">The file name to add to the Content-Disposition HTTP header on the response (optional)</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> TemporaryFilesGetTemporaryFileAsyncWithHttpInfo (string dataViewName, string id, string temporaryToken = null, string contentDispositionFileName = null)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFile");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFile");

            var localVarPath = "./{dataViewName}/TemporaryFiles/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (temporaryToken != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "temporaryToken", temporaryToken)); // query parameter
            if (contentDispositionFileName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "contentDispositionFileName", contentDispositionFileName)); // query parameter
            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TemporaryFilesGetTemporaryFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Returns the contents of a temporary file part with the given id and part number 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to return the contents for</param>
        /// <returns>byte[]</returns>
        public byte[] TemporaryFilesGetTemporaryFilePart (string dataViewName, string id, int? partNumber)
        {
             ApiResponse<byte[]> localVarResponse = TemporaryFilesGetTemporaryFilePartWithHttpInfo(dataViewName, id, partNumber);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the contents of a temporary file part with the given id and part number 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to return the contents for</param>
        /// <returns>ApiResponse of byte[]</returns>
        public ApiResponse< byte[] > TemporaryFilesGetTemporaryFilePartWithHttpInfo (string dataViewName, string id, int? partNumber)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFilePart");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFilePart");
            // verify the required parameter 'partNumber' is set
            if (partNumber == null)
                throw new ApiException(400, "Missing required parameter 'partNumber' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFilePart");

            var localVarPath = "./{dataViewName}/TemporaryFiles/{id}/{partNumber}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (partNumber != null) localVarPathParams.Add("partNumber", this.Configuration.ApiClient.ParameterToString(partNumber)); // path parameter
            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TemporaryFilesGetTemporaryFilePart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Returns the contents of a temporary file part with the given id and part number 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to return the contents for</param>
        /// <returns>Task of byte[]</returns>
        public async System.Threading.Tasks.Task<byte[]> TemporaryFilesGetTemporaryFilePartAsync (string dataViewName, string id, int? partNumber)
        {
             ApiResponse<byte[]> localVarResponse = await TemporaryFilesGetTemporaryFilePartAsyncWithHttpInfo(dataViewName, id, partNumber);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns the contents of a temporary file part with the given id and part number 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id of the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to return the contents for</param>
        /// <returns>Task of ApiResponse (byte[])</returns>
        public async System.Threading.Tasks.Task<ApiResponse<byte[]>> TemporaryFilesGetTemporaryFilePartAsyncWithHttpInfo (string dataViewName, string id, int? partNumber)
        {
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFilePart");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFilePart");
            // verify the required parameter 'partNumber' is set
            if (partNumber == null)
                throw new ApiException(400, "Missing required parameter 'partNumber' when calling TemporaryFilesApi->TemporaryFilesGetTemporaryFilePart");

            var localVarPath = "./{dataViewName}/TemporaryFiles/{id}/{partNumber}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (partNumber != null) localVarPathParams.Add("partNumber", this.Configuration.ApiClient.ParameterToString(partNumber)); // path parameter
            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TemporaryFilesGetTemporaryFilePart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<byte[]>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (byte[]) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
        }

        /// <summary>
        /// Creates or updates a temporary file with the given id 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file to create or update</param>
        /// <returns>TemporaryFile</returns>
        public TemporaryFile TemporaryFilesUpsertTemporaryFile (byte[] file, string dataViewName, string id)
        {
             ApiResponse<TemporaryFile> localVarResponse = TemporaryFilesUpsertTemporaryFileWithHttpInfo(file, dataViewName, id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates or updates a temporary file with the given id 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file to create or update</param>
        /// <returns>ApiResponse of TemporaryFile</returns>
        public ApiResponse< TemporaryFile > TemporaryFilesUpsertTemporaryFileWithHttpInfo (byte[] file, string dataViewName, string id)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFile");
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFile");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFile");

            var localVarPath = "./{dataViewName}/TemporaryFiles/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", file));
            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TemporaryFilesUpsertTemporaryFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TemporaryFile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (TemporaryFile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TemporaryFile)));
        }

        /// <summary>
        /// Creates or updates a temporary file with the given id 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file to create or update</param>
        /// <returns>Task of TemporaryFile</returns>
        public async System.Threading.Tasks.Task<TemporaryFile> TemporaryFilesUpsertTemporaryFileAsync (byte[] file, string dataViewName, string id)
        {
             ApiResponse<TemporaryFile> localVarResponse = await TemporaryFilesUpsertTemporaryFileAsyncWithHttpInfo(file, dataViewName, id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates or updates a temporary file with the given id 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file to create or update</param>
        /// <returns>Task of ApiResponse (TemporaryFile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TemporaryFile>> TemporaryFilesUpsertTemporaryFileAsyncWithHttpInfo (byte[] file, string dataViewName, string id)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFile");
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFile");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFile");

            var localVarPath = "./{dataViewName}/TemporaryFiles/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", file));
            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TemporaryFilesUpsertTemporaryFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TemporaryFile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (TemporaryFile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TemporaryFile)));
        }

        /// <summary>
        /// Creates or updates part of a temporary file with the given id and part number 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to create or update.  This is zero-based</param>
        /// <param name="finalPart">Whether this part is the final part and the full temporary file should be assembled.  If this is not specified it defaults to false.  If this is set to true all parts from 0 up to this partIndex must already exist (optional)</param>
        /// <returns>TemporaryFilePart</returns>
        public TemporaryFilePart TemporaryFilesUpsertTemporaryFilePart (byte[] file, string dataViewName, string id, int? partNumber, bool? finalPart = null)
        {
             ApiResponse<TemporaryFilePart> localVarResponse = TemporaryFilesUpsertTemporaryFilePartWithHttpInfo(file, dataViewName, id, partNumber, finalPart);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates or updates part of a temporary file with the given id and part number 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to create or update.  This is zero-based</param>
        /// <param name="finalPart">Whether this part is the final part and the full temporary file should be assembled.  If this is not specified it defaults to false.  If this is set to true all parts from 0 up to this partIndex must already exist (optional)</param>
        /// <returns>ApiResponse of TemporaryFilePart</returns>
        public ApiResponse< TemporaryFilePart > TemporaryFilesUpsertTemporaryFilePartWithHttpInfo (byte[] file, string dataViewName, string id, int? partNumber, bool? finalPart = null)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFilePart");
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFilePart");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFilePart");
            // verify the required parameter 'partNumber' is set
            if (partNumber == null)
                throw new ApiException(400, "Missing required parameter 'partNumber' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFilePart");

            var localVarPath = "./{dataViewName}/TemporaryFiles/{id}/{partNumber}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (partNumber != null) localVarPathParams.Add("partNumber", this.Configuration.ApiClient.ParameterToString(partNumber)); // path parameter
            if (finalPart != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "finalPart", finalPart)); // query parameter
            if (file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", file));
            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TemporaryFilesUpsertTemporaryFilePart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TemporaryFilePart>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (TemporaryFilePart) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TemporaryFilePart)));
        }

        /// <summary>
        /// Creates or updates part of a temporary file with the given id and part number 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to create or update.  This is zero-based</param>
        /// <param name="finalPart">Whether this part is the final part and the full temporary file should be assembled.  If this is not specified it defaults to false.  If this is set to true all parts from 0 up to this partIndex must already exist (optional)</param>
        /// <returns>Task of TemporaryFilePart</returns>
        public async System.Threading.Tasks.Task<TemporaryFilePart> TemporaryFilesUpsertTemporaryFilePartAsync (byte[] file, string dataViewName, string id, int? partNumber, bool? finalPart = null)
        {
             ApiResponse<TemporaryFilePart> localVarResponse = await TemporaryFilesUpsertTemporaryFilePartAsyncWithHttpInfo(file, dataViewName, id, partNumber, finalPart);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates or updates part of a temporary file with the given id and part number 
        /// </summary>
        /// <exception cref="Apteco.ApiRescheduler.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file"></param>
        /// <param name="dataViewName">The name of the DataView to act on</param>
        /// <param name="id">The id for the temporary file</param>
        /// <param name="partNumber">The number of the temporary file part to create or update.  This is zero-based</param>
        /// <param name="finalPart">Whether this part is the final part and the full temporary file should be assembled.  If this is not specified it defaults to false.  If this is set to true all parts from 0 up to this partIndex must already exist (optional)</param>
        /// <returns>Task of ApiResponse (TemporaryFilePart)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TemporaryFilePart>> TemporaryFilesUpsertTemporaryFilePartAsyncWithHttpInfo (byte[] file, string dataViewName, string id, int? partNumber, bool? finalPart = null)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFilePart");
            // verify the required parameter 'dataViewName' is set
            if (dataViewName == null)
                throw new ApiException(400, "Missing required parameter 'dataViewName' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFilePart");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFilePart");
            // verify the required parameter 'partNumber' is set
            if (partNumber == null)
                throw new ApiException(400, "Missing required parameter 'partNumber' when calling TemporaryFilesApi->TemporaryFilesUpsertTemporaryFilePart");

            var localVarPath = "./{dataViewName}/TemporaryFiles/{id}/{partNumber}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dataViewName != null) localVarPathParams.Add("dataViewName", this.Configuration.ApiClient.ParameterToString(dataViewName)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (partNumber != null) localVarPathParams.Add("partNumber", this.Configuration.ApiClient.ParameterToString(partNumber)); // path parameter
            if (finalPart != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "finalPart", finalPart)); // query parameter
            if (file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", file));
            // authentication (faststats_auth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TemporaryFilesUpsertTemporaryFilePart", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TemporaryFilePart>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (TemporaryFilePart) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TemporaryFilePart)));
        }

    }
}
