/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.ApiRescheduler.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.ApiRescheduler.ApiClient.Model
{
    /// <summary>
    /// Journey for a campaign
    /// </summary>
    [DataContract]
        public partial class CampaignJourneySummary :  IEquatable<CampaignJourneySummary>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CampaignJourneySummary" /> class.
        /// </summary>
        /// <param name="campaignId">campaignId.</param>
        /// <param name="journey">journey.</param>
        public CampaignJourneySummary(string campaignId = default(string), Journey journey = default(Journey))
        {
            this.CampaignId = campaignId;
            this.Journey = journey;
        }
        
        /// <summary>
        /// Gets or Sets CampaignId
        /// </summary>
        [DataMember(Name="campaignId", EmitDefaultValue=false)]
        public string CampaignId { get; set; }

        /// <summary>
        /// Gets or Sets Journey
        /// </summary>
        [DataMember(Name="journey", EmitDefaultValue=false)]
        public Journey Journey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CampaignJourneySummary {\n");
            sb.Append("  CampaignId: ").Append(CampaignId).Append("\n");
            sb.Append("  Journey: ").Append(Journey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CampaignJourneySummary);
        }

        /// <summary>
        /// Returns true if CampaignJourneySummary instances are equal
        /// </summary>
        /// <param name="input">Instance of CampaignJourneySummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CampaignJourneySummary input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CampaignId == input.CampaignId ||
                    (this.CampaignId != null &&
                    this.CampaignId.Equals(input.CampaignId))
                ) && 
                (
                    this.Journey == input.Journey ||
                    (this.Journey != null &&
                    this.Journey.Equals(input.Journey))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CampaignId != null)
                    hashCode = hashCode * 59 + this.CampaignId.GetHashCode();
                if (this.Journey != null)
                    hashCode = hashCode * 59 + this.Journey.GetHashCode();
                return hashCode;
            }
        }
    }
}
