/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.ApiRescheduler.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.ApiRescheduler.ApiClient.Model
{
    /// <summary>
    /// Details for an audience composition
    /// </summary>
    [DataContract]
        public partial class CompositionDetail :  IEquatable<CompositionDetail>
    {
        /// <summary>
        /// The type of this composition
        /// </summary>
        /// <value>The type of this composition</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum Check for value: Check
            /// </summary>
            [EnumMember(Value = "Check")]
            Check = 1        }
        /// <summary>
        /// The type of this composition
        /// </summary>
        /// <value>The type of this composition</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompositionDetail" /> class.
        /// </summary>
        /// <param name="checkCompositionDefinition">checkCompositionDefinition.</param>
        /// <param name="compositionsLookup">compositionsLookup.</param>
        /// <param name="id">The id of this composition (required).</param>
        /// <param name="description">The description of this composition (required).</param>
        /// <param name="type">The type of this composition (required).</param>
        /// <param name="systemName">The name of the FastStats system that this composition is for (required).</param>
        /// <param name="owner">owner (required).</param>
        /// <param name="numberOfUsersSharedWith">The number of people this composition has been shared with (required).</param>
        /// <param name="sharedToAll">Whether this composition has been shared to all users (required).</param>
        /// <param name="shareId">The id of the share associated with this composition, or null if the  composition has not yet been shared.</param>
        public CompositionDetail(CheckCompositionDefinition checkCompositionDefinition = default(CheckCompositionDefinition), SystemLookup compositionsLookup = default(SystemLookup), int? id = default(int?), string description = default(string), TypeEnum type = default(TypeEnum), string systemName = default(string), UserDisplayDetails owner = default(UserDisplayDetails), int? numberOfUsersSharedWith = default(int?), bool? sharedToAll = default(bool?), int? shareId = default(int?))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for CompositionDetail and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for CompositionDetail and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for CompositionDetail and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            // to ensure "systemName" is required (not null)
            if (systemName == null)
            {
                throw new InvalidDataException("systemName is a required property for CompositionDetail and cannot be null");
            }
            else
            {
                this.SystemName = systemName;
            }
            // to ensure "owner" is required (not null)
            if (owner == null)
            {
                throw new InvalidDataException("owner is a required property for CompositionDetail and cannot be null");
            }
            else
            {
                this.Owner = owner;
            }
            // to ensure "numberOfUsersSharedWith" is required (not null)
            if (numberOfUsersSharedWith == null)
            {
                throw new InvalidDataException("numberOfUsersSharedWith is a required property for CompositionDetail and cannot be null");
            }
            else
            {
                this.NumberOfUsersSharedWith = numberOfUsersSharedWith;
            }
            // to ensure "sharedToAll" is required (not null)
            if (sharedToAll == null)
            {
                throw new InvalidDataException("sharedToAll is a required property for CompositionDetail and cannot be null");
            }
            else
            {
                this.SharedToAll = sharedToAll;
            }
            this.CheckCompositionDefinition = checkCompositionDefinition;
            this.CompositionsLookup = compositionsLookup;
            this.ShareId = shareId;
        }
        
        /// <summary>
        /// Gets or Sets CheckCompositionDefinition
        /// </summary>
        [DataMember(Name="checkCompositionDefinition", EmitDefaultValue=false)]
        public CheckCompositionDefinition CheckCompositionDefinition { get; set; }

        /// <summary>
        /// Gets or Sets CompositionsLookup
        /// </summary>
        [DataMember(Name="compositionsLookup", EmitDefaultValue=false)]
        public SystemLookup CompositionsLookup { get; set; }

        /// <summary>
        /// The id of this composition
        /// </summary>
        /// <value>The id of this composition</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// The description of this composition
        /// </summary>
        /// <value>The description of this composition</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }


        /// <summary>
        /// The name of the FastStats system that this composition is for
        /// </summary>
        /// <value>The name of the FastStats system that this composition is for</value>
        [DataMember(Name="systemName", EmitDefaultValue=false)]
        public string SystemName { get; set; }

        /// <summary>
        /// Gets or Sets Owner
        /// </summary>
        [DataMember(Name="owner", EmitDefaultValue=false)]
        public UserDisplayDetails Owner { get; set; }

        /// <summary>
        /// The number of people this composition has been shared with
        /// </summary>
        /// <value>The number of people this composition has been shared with</value>
        [DataMember(Name="numberOfUsersSharedWith", EmitDefaultValue=false)]
        public int? NumberOfUsersSharedWith { get; set; }

        /// <summary>
        /// Whether this composition has been shared to all users
        /// </summary>
        /// <value>Whether this composition has been shared to all users</value>
        [DataMember(Name="sharedToAll", EmitDefaultValue=false)]
        public bool? SharedToAll { get; set; }

        /// <summary>
        /// The id of the share associated with this composition, or null if the  composition has not yet been shared
        /// </summary>
        /// <value>The id of the share associated with this composition, or null if the  composition has not yet been shared</value>
        [DataMember(Name="shareId", EmitDefaultValue=false)]
        public int? ShareId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompositionDetail {\n");
            sb.Append("  CheckCompositionDefinition: ").Append(CheckCompositionDefinition).Append("\n");
            sb.Append("  CompositionsLookup: ").Append(CompositionsLookup).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  SystemName: ").Append(SystemName).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  NumberOfUsersSharedWith: ").Append(NumberOfUsersSharedWith).Append("\n");
            sb.Append("  SharedToAll: ").Append(SharedToAll).Append("\n");
            sb.Append("  ShareId: ").Append(ShareId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CompositionDetail);
        }

        /// <summary>
        /// Returns true if CompositionDetail instances are equal
        /// </summary>
        /// <param name="input">Instance of CompositionDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompositionDetail input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CheckCompositionDefinition == input.CheckCompositionDefinition ||
                    (this.CheckCompositionDefinition != null &&
                    this.CheckCompositionDefinition.Equals(input.CheckCompositionDefinition))
                ) && 
                (
                    this.CompositionsLookup == input.CompositionsLookup ||
                    (this.CompositionsLookup != null &&
                    this.CompositionsLookup.Equals(input.CompositionsLookup))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.SystemName == input.SystemName ||
                    (this.SystemName != null &&
                    this.SystemName.Equals(input.SystemName))
                ) && 
                (
                    this.Owner == input.Owner ||
                    (this.Owner != null &&
                    this.Owner.Equals(input.Owner))
                ) && 
                (
                    this.NumberOfUsersSharedWith == input.NumberOfUsersSharedWith ||
                    (this.NumberOfUsersSharedWith != null &&
                    this.NumberOfUsersSharedWith.Equals(input.NumberOfUsersSharedWith))
                ) && 
                (
                    this.SharedToAll == input.SharedToAll ||
                    (this.SharedToAll != null &&
                    this.SharedToAll.Equals(input.SharedToAll))
                ) && 
                (
                    this.ShareId == input.ShareId ||
                    (this.ShareId != null &&
                    this.ShareId.Equals(input.ShareId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CheckCompositionDefinition != null)
                    hashCode = hashCode * 59 + this.CheckCompositionDefinition.GetHashCode();
                if (this.CompositionsLookup != null)
                    hashCode = hashCode * 59 + this.CompositionsLookup.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.SystemName != null)
                    hashCode = hashCode * 59 + this.SystemName.GetHashCode();
                if (this.Owner != null)
                    hashCode = hashCode * 59 + this.Owner.GetHashCode();
                if (this.NumberOfUsersSharedWith != null)
                    hashCode = hashCode * 59 + this.NumberOfUsersSharedWith.GetHashCode();
                if (this.SharedToAll != null)
                    hashCode = hashCode * 59 + this.SharedToAll.GetHashCode();
                if (this.ShareId != null)
                    hashCode = hashCode * 59 + this.ShareId.GetHashCode();
                return hashCode;
            }
        }
    }
}
