/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.ApiRescheduler.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.ApiRescheduler.ApiClient.Model
{
    /// <summary>
    /// Permission
    /// </summary>
    [DataContract]
        public partial class Permission :  IEquatable<Permission>
    {
        /// <summary>
        /// Defines PermissionType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum PermissionTypeEnum
        {
            /// <summary>
            /// Enum Unknown for value: Unknown
            /// </summary>
            [EnumMember(Value = "Unknown")]
            Unknown = 1,
            /// <summary>
            /// Enum AccessRights for value: AccessRights
            /// </summary>
            [EnumMember(Value = "AccessRights")]
            AccessRights = 2,
            /// <summary>
            /// Enum UsageRights for value: UsageRights
            /// </summary>
            [EnumMember(Value = "UsageRights")]
            UsageRights = 3,
            /// <summary>
            /// Enum VariableUsageRights for value: VariableUsageRights
            /// </summary>
            [EnumMember(Value = "VariableUsageRights")]
            VariableUsageRights = 4        }
        /// <summary>
        /// Gets or Sets PermissionType
        /// </summary>
        [DataMember(Name="permissionType", EmitDefaultValue=false)]
        public PermissionTypeEnum PermissionType { get; set; }
        /// <summary>
        /// Defines ResourceType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ResourceTypeEnum
        {
            /// <summary>
            /// Enum Unknown for value: Unknown
            /// </summary>
            [EnumMember(Value = "Unknown")]
            Unknown = 1,
            /// <summary>
            /// Enum File for value: File
            /// </summary>
            [EnumMember(Value = "File")]
            File = 2,
            /// <summary>
            /// Enum PeopleStageElement for value: PeopleStageElement
            /// </summary>
            [EnumMember(Value = "PeopleStageElement")]
            PeopleStageElement = 3,
            /// <summary>
            /// Enum PeopleStageDiagram for value: PeopleStageDiagram
            /// </summary>
            [EnumMember(Value = "PeopleStageDiagram")]
            PeopleStageDiagram = 4,
            /// <summary>
            /// Enum PeopleStageSeed for value: PeopleStageSeed
            /// </summary>
            [EnumMember(Value = "PeopleStageSeed")]
            PeopleStageSeed = 5,
            /// <summary>
            /// Enum PeopleStageSeedSet for value: PeopleStageSeedSet
            /// </summary>
            [EnumMember(Value = "PeopleStageSeedSet")]
            PeopleStageSeedSet = 6,
            /// <summary>
            /// Enum PeopleStageChannel for value: PeopleStageChannel
            /// </summary>
            [EnumMember(Value = "PeopleStageChannel")]
            PeopleStageChannel = 7,
            /// <summary>
            /// Enum PeopleStageAggregation for value: PeopleStageAggregation
            /// </summary>
            [EnumMember(Value = "PeopleStageAggregation")]
            PeopleStageAggregation = 8,
            /// <summary>
            /// Enum PeopleStageVoucherSet for value: PeopleStageVoucherSet
            /// </summary>
            [EnumMember(Value = "PeopleStageVoucherSet")]
            PeopleStageVoucherSet = 9,
            /// <summary>
            /// Enum PeopleStageTemplate for value: PeopleStageTemplate
            /// </summary>
            [EnumMember(Value = "PeopleStageTemplate")]
            PeopleStageTemplate = 10,
            /// <summary>
            /// Enum CascadeElement for value: CascadeElement
            /// </summary>
            [EnumMember(Value = "CascadeElement")]
            CascadeElement = 11,
            /// <summary>
            /// Enum FastStatsElement for value: FastStatsElement
            /// </summary>
            [EnumMember(Value = "FastStatsElement")]
            FastStatsElement = 12,
            /// <summary>
            /// Enum UserElement for value: UserElement
            /// </summary>
            [EnumMember(Value = "UserElement")]
            UserElement = 13,
            /// <summary>
            /// Enum FtpSite for value: FtpSite
            /// </summary>
            [EnumMember(Value = "FtpSite")]
            FtpSite = 14,
            /// <summary>
            /// Enum StorageQuota for value: StorageQuota
            /// </summary>
            [EnumMember(Value = "StorageQuota")]
            StorageQuota = 15,
            /// <summary>
            /// Enum Velocity for value: Velocity
            /// </summary>
            [EnumMember(Value = "Velocity")]
            Velocity = 16,
            /// <summary>
            /// Enum RowFilter for value: RowFilter
            /// </summary>
            [EnumMember(Value = "RowFilter")]
            RowFilter = 17,
            /// <summary>
            /// Enum UsersAdmin for value: UsersAdmin
            /// </summary>
            [EnumMember(Value = "UsersAdmin")]
            UsersAdmin = 18,
            /// <summary>
            /// Enum DataControlAdmin for value: DataControlAdmin
            /// </summary>
            [EnumMember(Value = "DataControlAdmin")]
            DataControlAdmin = 19,
            /// <summary>
            /// Enum IntegrationsAdmin for value: IntegrationsAdmin
            /// </summary>
            [EnumMember(Value = "IntegrationsAdmin")]
            IntegrationsAdmin = 20,
            /// <summary>
            /// Enum OrbitFeatures for value: OrbitFeatures
            /// </summary>
            [EnumMember(Value = "OrbitFeatures")]
            OrbitFeatures = 21,
            /// <summary>
            /// Enum OrbitDashboard for value: OrbitDashboard
            /// </summary>
            [EnumMember(Value = "OrbitDashboard")]
            OrbitDashboard = 22,
            /// <summary>
            /// Enum OrbitAudience for value: OrbitAudience
            /// </summary>
            [EnumMember(Value = "OrbitAudience")]
            OrbitAudience = 23,
            /// <summary>
            /// Enum OrbitAudienceExportTemplate for value: OrbitAudienceExportTemplate
            /// </summary>
            [EnumMember(Value = "OrbitAudienceExportTemplate")]
            OrbitAudienceExportTemplate = 24,
            /// <summary>
            /// Enum SupportAdmin for value: SupportAdmin
            /// </summary>
            [EnumMember(Value = "SupportAdmin")]
            SupportAdmin = 25,
            /// <summary>
            /// Enum OrbitCollection for value: OrbitCollection
            /// </summary>
            [EnumMember(Value = "OrbitCollection")]
            OrbitCollection = 26        }
        /// <summary>
        /// Gets or Sets ResourceType
        /// </summary>
        [DataMember(Name="resourceType", EmitDefaultValue=false)]
        public ResourceTypeEnum ResourceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Permission" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="permission">permission.</param>
        /// <param name="permissionType">permissionType (required).</param>
        /// <param name="resource">resource.</param>
        /// <param name="resourceType">resourceType (required).</param>
        /// <param name="grant">grant (required).</param>
        /// <param name="deny">deny (required).</param>
        /// <param name="inherit">inherit (required).</param>
        public Permission(int? id = default(int?), Object permission = default(Object), PermissionTypeEnum permissionType = default(PermissionTypeEnum), string resource = default(string), ResourceTypeEnum resourceType = default(ResourceTypeEnum), bool? grant = default(bool?), bool? deny = default(bool?), bool? inherit = default(bool?))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for Permission and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "permissionType" is required (not null)
            if (permissionType == null)
            {
                throw new InvalidDataException("permissionType is a required property for Permission and cannot be null");
            }
            else
            {
                this.PermissionType = permissionType;
            }
            // to ensure "resourceType" is required (not null)
            if (resourceType == null)
            {
                throw new InvalidDataException("resourceType is a required property for Permission and cannot be null");
            }
            else
            {
                this.ResourceType = resourceType;
            }
            // to ensure "grant" is required (not null)
            if (grant == null)
            {
                throw new InvalidDataException("grant is a required property for Permission and cannot be null");
            }
            else
            {
                this.Grant = grant;
            }
            // to ensure "deny" is required (not null)
            if (deny == null)
            {
                throw new InvalidDataException("deny is a required property for Permission and cannot be null");
            }
            else
            {
                this.Deny = deny;
            }
            // to ensure "inherit" is required (not null)
            if (inherit == null)
            {
                throw new InvalidDataException("inherit is a required property for Permission and cannot be null");
            }
            else
            {
                this.Inherit = inherit;
            }
            this._Permission = permission;
            this.Resource = resource;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets _Permission
        /// </summary>
        [DataMember(Name="permission", EmitDefaultValue=false)]
        public Object _Permission { get; set; }


        /// <summary>
        /// Gets or Sets Resource
        /// </summary>
        [DataMember(Name="resource", EmitDefaultValue=false)]
        public string Resource { get; set; }


        /// <summary>
        /// Gets or Sets Grant
        /// </summary>
        [DataMember(Name="grant", EmitDefaultValue=false)]
        public bool? Grant { get; set; }

        /// <summary>
        /// Gets or Sets Deny
        /// </summary>
        [DataMember(Name="deny", EmitDefaultValue=false)]
        public bool? Deny { get; set; }

        /// <summary>
        /// Gets or Sets Inherit
        /// </summary>
        [DataMember(Name="inherit", EmitDefaultValue=false)]
        public bool? Inherit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Permission {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  _Permission: ").Append(_Permission).Append("\n");
            sb.Append("  PermissionType: ").Append(PermissionType).Append("\n");
            sb.Append("  Resource: ").Append(Resource).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  Grant: ").Append(Grant).Append("\n");
            sb.Append("  Deny: ").Append(Deny).Append("\n");
            sb.Append("  Inherit: ").Append(Inherit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Permission);
        }

        /// <summary>
        /// Returns true if Permission instances are equal
        /// </summary>
        /// <param name="input">Instance of Permission to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Permission input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this._Permission == input._Permission ||
                    (this._Permission != null &&
                    this._Permission.Equals(input._Permission))
                ) && 
                (
                    this.PermissionType == input.PermissionType ||
                    (this.PermissionType != null &&
                    this.PermissionType.Equals(input.PermissionType))
                ) && 
                (
                    this.Resource == input.Resource ||
                    (this.Resource != null &&
                    this.Resource.Equals(input.Resource))
                ) && 
                (
                    this.ResourceType == input.ResourceType ||
                    (this.ResourceType != null &&
                    this.ResourceType.Equals(input.ResourceType))
                ) && 
                (
                    this.Grant == input.Grant ||
                    (this.Grant != null &&
                    this.Grant.Equals(input.Grant))
                ) && 
                (
                    this.Deny == input.Deny ||
                    (this.Deny != null &&
                    this.Deny.Equals(input.Deny))
                ) && 
                (
                    this.Inherit == input.Inherit ||
                    (this.Inherit != null &&
                    this.Inherit.Equals(input.Inherit))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this._Permission != null)
                    hashCode = hashCode * 59 + this._Permission.GetHashCode();
                if (this.PermissionType != null)
                    hashCode = hashCode * 59 + this.PermissionType.GetHashCode();
                if (this.Resource != null)
                    hashCode = hashCode * 59 + this.Resource.GetHashCode();
                if (this.ResourceType != null)
                    hashCode = hashCode * 59 + this.ResourceType.GetHashCode();
                if (this.Grant != null)
                    hashCode = hashCode * 59 + this.Grant.GetHashCode();
                if (this.Deny != null)
                    hashCode = hashCode * 59 + this.Deny.GetHashCode();
                if (this.Inherit != null)
                    hashCode = hashCode * 59 + this.Inherit.GetHashCode();
                return hashCode;
            }
        }
    }
}
