/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.ApiRescheduler.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.ApiRescheduler.ApiClient.Model
{
    /// <summary>
    /// ResolvedPermissionSummaryWithLookups
    /// </summary>
    [DataContract]
        public partial class ResolvedPermissionSummaryWithLookups :  IEquatable<ResolvedPermissionSummaryWithLookups>
    {
        /// <summary>
        /// Defines PermissionType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum PermissionTypeEnum
        {
            /// <summary>
            /// Enum Unknown for value: Unknown
            /// </summary>
            [EnumMember(Value = "Unknown")]
            Unknown = 1,
            /// <summary>
            /// Enum AccessRights for value: AccessRights
            /// </summary>
            [EnumMember(Value = "AccessRights")]
            AccessRights = 2,
            /// <summary>
            /// Enum UsageRights for value: UsageRights
            /// </summary>
            [EnumMember(Value = "UsageRights")]
            UsageRights = 3,
            /// <summary>
            /// Enum VariableUsageRights for value: VariableUsageRights
            /// </summary>
            [EnumMember(Value = "VariableUsageRights")]
            VariableUsageRights = 4        }
        /// <summary>
        /// Gets or Sets PermissionType
        /// </summary>
        [DataMember(Name="permissionType", EmitDefaultValue=false)]
        public PermissionTypeEnum PermissionType { get; set; }
        /// <summary>
        /// Defines ResourceType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum ResourceTypeEnum
        {
            /// <summary>
            /// Enum Unknown for value: Unknown
            /// </summary>
            [EnumMember(Value = "Unknown")]
            Unknown = 1,
            /// <summary>
            /// Enum File for value: File
            /// </summary>
            [EnumMember(Value = "File")]
            File = 2,
            /// <summary>
            /// Enum PeopleStageElement for value: PeopleStageElement
            /// </summary>
            [EnumMember(Value = "PeopleStageElement")]
            PeopleStageElement = 3,
            /// <summary>
            /// Enum PeopleStageDiagram for value: PeopleStageDiagram
            /// </summary>
            [EnumMember(Value = "PeopleStageDiagram")]
            PeopleStageDiagram = 4,
            /// <summary>
            /// Enum PeopleStageSeed for value: PeopleStageSeed
            /// </summary>
            [EnumMember(Value = "PeopleStageSeed")]
            PeopleStageSeed = 5,
            /// <summary>
            /// Enum PeopleStageSeedSet for value: PeopleStageSeedSet
            /// </summary>
            [EnumMember(Value = "PeopleStageSeedSet")]
            PeopleStageSeedSet = 6,
            /// <summary>
            /// Enum PeopleStageChannel for value: PeopleStageChannel
            /// </summary>
            [EnumMember(Value = "PeopleStageChannel")]
            PeopleStageChannel = 7,
            /// <summary>
            /// Enum PeopleStageAggregation for value: PeopleStageAggregation
            /// </summary>
            [EnumMember(Value = "PeopleStageAggregation")]
            PeopleStageAggregation = 8,
            /// <summary>
            /// Enum PeopleStageVoucherSet for value: PeopleStageVoucherSet
            /// </summary>
            [EnumMember(Value = "PeopleStageVoucherSet")]
            PeopleStageVoucherSet = 9,
            /// <summary>
            /// Enum PeopleStageTemplate for value: PeopleStageTemplate
            /// </summary>
            [EnumMember(Value = "PeopleStageTemplate")]
            PeopleStageTemplate = 10,
            /// <summary>
            /// Enum CascadeElement for value: CascadeElement
            /// </summary>
            [EnumMember(Value = "CascadeElement")]
            CascadeElement = 11,
            /// <summary>
            /// Enum FastStatsElement for value: FastStatsElement
            /// </summary>
            [EnumMember(Value = "FastStatsElement")]
            FastStatsElement = 12,
            /// <summary>
            /// Enum UserElement for value: UserElement
            /// </summary>
            [EnumMember(Value = "UserElement")]
            UserElement = 13,
            /// <summary>
            /// Enum FtpSite for value: FtpSite
            /// </summary>
            [EnumMember(Value = "FtpSite")]
            FtpSite = 14,
            /// <summary>
            /// Enum StorageQuota for value: StorageQuota
            /// </summary>
            [EnumMember(Value = "StorageQuota")]
            StorageQuota = 15,
            /// <summary>
            /// Enum Velocity for value: Velocity
            /// </summary>
            [EnumMember(Value = "Velocity")]
            Velocity = 16,
            /// <summary>
            /// Enum RowFilter for value: RowFilter
            /// </summary>
            [EnumMember(Value = "RowFilter")]
            RowFilter = 17,
            /// <summary>
            /// Enum UsersAdmin for value: UsersAdmin
            /// </summary>
            [EnumMember(Value = "UsersAdmin")]
            UsersAdmin = 18,
            /// <summary>
            /// Enum DataControlAdmin for value: DataControlAdmin
            /// </summary>
            [EnumMember(Value = "DataControlAdmin")]
            DataControlAdmin = 19,
            /// <summary>
            /// Enum IntegrationsAdmin for value: IntegrationsAdmin
            /// </summary>
            [EnumMember(Value = "IntegrationsAdmin")]
            IntegrationsAdmin = 20,
            /// <summary>
            /// Enum OrbitFeatures for value: OrbitFeatures
            /// </summary>
            [EnumMember(Value = "OrbitFeatures")]
            OrbitFeatures = 21,
            /// <summary>
            /// Enum OrbitDashboard for value: OrbitDashboard
            /// </summary>
            [EnumMember(Value = "OrbitDashboard")]
            OrbitDashboard = 22,
            /// <summary>
            /// Enum OrbitAudience for value: OrbitAudience
            /// </summary>
            [EnumMember(Value = "OrbitAudience")]
            OrbitAudience = 23,
            /// <summary>
            /// Enum OrbitAudienceExportTemplate for value: OrbitAudienceExportTemplate
            /// </summary>
            [EnumMember(Value = "OrbitAudienceExportTemplate")]
            OrbitAudienceExportTemplate = 24,
            /// <summary>
            /// Enum SupportAdmin for value: SupportAdmin
            /// </summary>
            [EnumMember(Value = "SupportAdmin")]
            SupportAdmin = 25,
            /// <summary>
            /// Enum OrbitCollection for value: OrbitCollection
            /// </summary>
            [EnumMember(Value = "OrbitCollection")]
            OrbitCollection = 26        }
        /// <summary>
        /// Gets or Sets ResourceType
        /// </summary>
        [DataMember(Name="resourceType", EmitDefaultValue=false)]
        public ResourceTypeEnum ResourceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResolvedPermissionSummaryWithLookups" /> class.
        /// </summary>
        /// <param name="resource">resource (required).</param>
        /// <param name="resourceExists">resourceExists (required).</param>
        /// <param name="permissionType">permissionType (required).</param>
        /// <param name="resourceType">resourceType (required).</param>
        /// <param name="permissionPieces">permissionPieces (required).</param>
        /// <param name="permissionsCount">permissionsCount (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="lookups">lookups (required).</param>
        public ResolvedPermissionSummaryWithLookups(string resource = default(string), bool? resourceExists = default(bool?), PermissionTypeEnum permissionType = default(PermissionTypeEnum), ResourceTypeEnum resourceType = default(ResourceTypeEnum), List<PermissionPiece> permissionPieces = default(List<PermissionPiece>), int? permissionsCount = default(int?), Id id = default(Id), Lookups lookups = default(Lookups))
        {
            // to ensure "resource" is required (not null)
            if (resource == null)
            {
                throw new InvalidDataException("resource is a required property for ResolvedPermissionSummaryWithLookups and cannot be null");
            }
            else
            {
                this.Resource = resource;
            }
            // to ensure "resourceExists" is required (not null)
            if (resourceExists == null)
            {
                throw new InvalidDataException("resourceExists is a required property for ResolvedPermissionSummaryWithLookups and cannot be null");
            }
            else
            {
                this.ResourceExists = resourceExists;
            }
            // to ensure "permissionType" is required (not null)
            if (permissionType == null)
            {
                throw new InvalidDataException("permissionType is a required property for ResolvedPermissionSummaryWithLookups and cannot be null");
            }
            else
            {
                this.PermissionType = permissionType;
            }
            // to ensure "resourceType" is required (not null)
            if (resourceType == null)
            {
                throw new InvalidDataException("resourceType is a required property for ResolvedPermissionSummaryWithLookups and cannot be null");
            }
            else
            {
                this.ResourceType = resourceType;
            }
            // to ensure "permissionPieces" is required (not null)
            if (permissionPieces == null)
            {
                throw new InvalidDataException("permissionPieces is a required property for ResolvedPermissionSummaryWithLookups and cannot be null");
            }
            else
            {
                this.PermissionPieces = permissionPieces;
            }
            // to ensure "permissionsCount" is required (not null)
            if (permissionsCount == null)
            {
                throw new InvalidDataException("permissionsCount is a required property for ResolvedPermissionSummaryWithLookups and cannot be null");
            }
            else
            {
                this.PermissionsCount = permissionsCount;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for ResolvedPermissionSummaryWithLookups and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "lookups" is required (not null)
            if (lookups == null)
            {
                throw new InvalidDataException("lookups is a required property for ResolvedPermissionSummaryWithLookups and cannot be null");
            }
            else
            {
                this.Lookups = lookups;
            }
        }
        
        /// <summary>
        /// Gets or Sets Resource
        /// </summary>
        [DataMember(Name="resource", EmitDefaultValue=false)]
        public string Resource { get; set; }

        /// <summary>
        /// Gets or Sets ResourceExists
        /// </summary>
        [DataMember(Name="resourceExists", EmitDefaultValue=false)]
        public bool? ResourceExists { get; set; }



        /// <summary>
        /// Gets or Sets PermissionPieces
        /// </summary>
        [DataMember(Name="permissionPieces", EmitDefaultValue=false)]
        public List<PermissionPiece> PermissionPieces { get; set; }

        /// <summary>
        /// Gets or Sets PermissionsCount
        /// </summary>
        [DataMember(Name="permissionsCount", EmitDefaultValue=false)]
        public int? PermissionsCount { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public Id Id { get; set; }

        /// <summary>
        /// Gets or Sets Lookups
        /// </summary>
        [DataMember(Name="lookups", EmitDefaultValue=false)]
        public Lookups Lookups { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResolvedPermissionSummaryWithLookups {\n");
            sb.Append("  Resource: ").Append(Resource).Append("\n");
            sb.Append("  ResourceExists: ").Append(ResourceExists).Append("\n");
            sb.Append("  PermissionType: ").Append(PermissionType).Append("\n");
            sb.Append("  ResourceType: ").Append(ResourceType).Append("\n");
            sb.Append("  PermissionPieces: ").Append(PermissionPieces).Append("\n");
            sb.Append("  PermissionsCount: ").Append(PermissionsCount).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Lookups: ").Append(Lookups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResolvedPermissionSummaryWithLookups);
        }

        /// <summary>
        /// Returns true if ResolvedPermissionSummaryWithLookups instances are equal
        /// </summary>
        /// <param name="input">Instance of ResolvedPermissionSummaryWithLookups to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResolvedPermissionSummaryWithLookups input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Resource == input.Resource ||
                    (this.Resource != null &&
                    this.Resource.Equals(input.Resource))
                ) && 
                (
                    this.ResourceExists == input.ResourceExists ||
                    (this.ResourceExists != null &&
                    this.ResourceExists.Equals(input.ResourceExists))
                ) && 
                (
                    this.PermissionType == input.PermissionType ||
                    (this.PermissionType != null &&
                    this.PermissionType.Equals(input.PermissionType))
                ) && 
                (
                    this.ResourceType == input.ResourceType ||
                    (this.ResourceType != null &&
                    this.ResourceType.Equals(input.ResourceType))
                ) && 
                (
                    this.PermissionPieces == input.PermissionPieces ||
                    this.PermissionPieces != null &&
                    input.PermissionPieces != null &&
                    this.PermissionPieces.SequenceEqual(input.PermissionPieces)
                ) && 
                (
                    this.PermissionsCount == input.PermissionsCount ||
                    (this.PermissionsCount != null &&
                    this.PermissionsCount.Equals(input.PermissionsCount))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Lookups == input.Lookups ||
                    (this.Lookups != null &&
                    this.Lookups.Equals(input.Lookups))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Resource != null)
                    hashCode = hashCode * 59 + this.Resource.GetHashCode();
                if (this.ResourceExists != null)
                    hashCode = hashCode * 59 + this.ResourceExists.GetHashCode();
                if (this.PermissionType != null)
                    hashCode = hashCode * 59 + this.PermissionType.GetHashCode();
                if (this.ResourceType != null)
                    hashCode = hashCode * 59 + this.ResourceType.GetHashCode();
                if (this.PermissionPieces != null)
                    hashCode = hashCode * 59 + this.PermissionPieces.GetHashCode();
                if (this.PermissionsCount != null)
                    hashCode = hashCode * 59 + this.PermissionsCount.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Lookups != null)
                    hashCode = hashCode * 59 + this.Lookups.GetHashCode();
                return hashCode;
            }
        }
    }
}
