/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.ApiRescheduler.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.ApiRescheduler.ApiClient.Model
{
    /// <summary>
    /// Details specific for text variables in the FastStats system
    /// </summary>
    [DataContract]
        public partial class TextVariableInfo :  IEquatable<TextVariableInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextVariableInfo" /> class.
        /// </summary>
        /// <param name="maximumTextLength">The maximum length of text data (in bytes) that can be held in the variable per record.</param>
        public TextVariableInfo(int? maximumTextLength = default(int?))
        {
            this.MaximumTextLength = maximumTextLength;
        }
        
        /// <summary>
        /// The maximum length of text data (in bytes) that can be held in the variable per record
        /// </summary>
        /// <value>The maximum length of text data (in bytes) that can be held in the variable per record</value>
        [DataMember(Name="maximumTextLength", EmitDefaultValue=false)]
        public int? MaximumTextLength { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TextVariableInfo {\n");
            sb.Append("  MaximumTextLength: ").Append(MaximumTextLength).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TextVariableInfo);
        }

        /// <summary>
        /// Returns true if TextVariableInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of TextVariableInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TextVariableInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MaximumTextLength == input.MaximumTextLength ||
                    (this.MaximumTextLength != null &&
                    this.MaximumTextLength.Equals(input.MaximumTextLength))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MaximumTextLength != null)
                    hashCode = hashCode * 59 + this.MaximumTextLength.GetHashCode();
                return hashCode;
            }
        }
    }
}
