/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.ApiRescheduler.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.ApiRescheduler.ApiClient.Model
{
    /// <summary>
    /// TupleInt32AccessRightsEnum
    /// </summary>
    [DataContract]
        public partial class TupleInt32AccessRightsEnum :  IEquatable<TupleInt32AccessRightsEnum>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TupleInt32AccessRightsEnum" /> class.
        /// </summary>
        /// <param name="item1">item1.</param>
        /// <param name="item2">item2.</param>
        public TupleInt32AccessRightsEnum(int? item1 = default(int?), int? item2 = default(int?))
        {
            this.Item1 = item1;
            this.Item2 = item2;
        }
        
        /// <summary>
        /// Gets or Sets Item1
        /// </summary>
        [DataMember(Name="item1", EmitDefaultValue=false)]
        public int? Item1 { get; set; }

        /// <summary>
        /// Gets or Sets Item2
        /// </summary>
        [DataMember(Name="item2", EmitDefaultValue=false)]
        public int? Item2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TupleInt32AccessRightsEnum {\n");
            sb.Append("  Item1: ").Append(Item1).Append("\n");
            sb.Append("  Item2: ").Append(Item2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TupleInt32AccessRightsEnum);
        }

        /// <summary>
        /// Returns true if TupleInt32AccessRightsEnum instances are equal
        /// </summary>
        /// <param name="input">Instance of TupleInt32AccessRightsEnum to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TupleInt32AccessRightsEnum input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Item1 == input.Item1 ||
                    (this.Item1 != null &&
                    this.Item1.Equals(input.Item1))
                ) && 
                (
                    this.Item2 == input.Item2 ||
                    (this.Item2 != null &&
                    this.Item2.Equals(input.Item2))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Item1 != null)
                    hashCode = hashCode * 59 + this.Item1.GetHashCode();
                if (this.Item2 != null)
                    hashCode = hashCode * 59 + this.Item2.GetHashCode();
                return hashCode;
            }
        }
    }
}
