/* 
 * Apteco API
 *
 * An API to allow access to Apteco Marketing Suite resources
 *
 * OpenAPI spec version: v2
 * Contact: support@apteco.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Apteco.ApiRescheduler.ApiClient.Client.SwaggerDateConverter;

namespace Apteco.ApiRescheduler.ApiClient.Model
{
    /// <summary>
    /// Velocity details for a system
    /// </summary>
    [DataContract]
        public partial class VelocityDetails :  IEquatable<VelocityDetails>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VelocityDetails" /> class.
        /// </summary>
        /// <param name="velocities">The velocities (required).</param>
        /// <param name="tagsLookup">tagsLookup.</param>
        public VelocityDetails(List<Velocity> velocities = default(List<Velocity>), TagsLookup tagsLookup = default(TagsLookup))
        {
            // to ensure "velocities" is required (not null)
            if (velocities == null)
            {
                throw new InvalidDataException("velocities is a required property for VelocityDetails and cannot be null");
            }
            else
            {
                this.Velocities = velocities;
            }
            this.TagsLookup = tagsLookup;
        }
        
        /// <summary>
        /// The velocities
        /// </summary>
        /// <value>The velocities</value>
        [DataMember(Name="velocities", EmitDefaultValue=false)]
        public List<Velocity> Velocities { get; set; }

        /// <summary>
        /// Gets or Sets TagsLookup
        /// </summary>
        [DataMember(Name="tagsLookup", EmitDefaultValue=false)]
        public TagsLookup TagsLookup { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VelocityDetails {\n");
            sb.Append("  Velocities: ").Append(Velocities).Append("\n");
            sb.Append("  TagsLookup: ").Append(TagsLookup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VelocityDetails);
        }

        /// <summary>
        /// Returns true if VelocityDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of VelocityDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VelocityDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Velocities == input.Velocities ||
                    this.Velocities != null &&
                    input.Velocities != null &&
                    this.Velocities.SequenceEqual(input.Velocities)
                ) && 
                (
                    this.TagsLookup == input.TagsLookup ||
                    (this.TagsLookup != null &&
                    this.TagsLookup.Equals(input.TagsLookup))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Velocities != null)
                    hashCode = hashCode * 59 + this.Velocities.GetHashCode();
                if (this.TagsLookup != null)
                    hashCode = hashCode * 59 + this.TagsLookup.GetHashCode();
                return hashCode;
            }
        }
    }
}
